### PR TITLE
Avoid generating code using unstable features for std::backtrace

### PR DESCRIPTION
**Pull request by andrewaylett**
With std::backtrace being available in stable releases, we should avoid generating code that uses nightly-only APIs unless the relevant nightly features are in use.

### CODE REVIEW

**Review by dtolnay — CHANGES_REQUESTED** [review]
Thanks for the PR!

If I understand correctly, this silently ignores a field of type `Backtrace` if the compiler isn't nightly?

I am okay with this but only if you can make it validate that the Backtrace is of type `std::backtrace::Backtrace`, as opposed to some other type called `Backtrace`. This avoid the possibility of needing a breaking change later when we do plug that field into the Error trait assuming it's a standard library backtrace.

**Comment by andrewaylett** [comment]
Currently we assume that the presence of `std::backtrace::Backtrace` implies the presence of `std::any::Provider`.  `std::error::Error` [defines](https://doc.rust-lang.org/std/error/trait.Error.html#method.provide) a nightly-only `provide` function which we unconditionally generate code for when `Backtrace` is present, but as the generated code relies on nightly-only APIs (and doesn't actually exist on the trait), this fails on stable Rust.

So the intent of the code is to move away from assuming that if we have one of `Backtrace` and `Provide` then we'll have both of them, and instead check for each of the features separately.

When the `error_generic_member_access` feature is stabilised, we'll start generating this code again and override the default trait impl without needing further changes.

**Comment by dtolnay** [comment]
> When the `error_generic_member_access` feature is stabilised, we'll start generating this code again and override the default trait impl without needing further changes.

Yes, this is the problem. This is the point at which people's existing code will break if those backtrace fields were not of the right type, unless you address the suggestion from the review.

**Review by dtolnay — COMMENTED** [review]
I tried implementing the future-compatible approach in #268 but I didn't get it to work in a way that I would want, so I think keeping the current logic is the only option.

Thanks anyway for working on this!

**Pull request closed without merging**
